spring:
  application:
    name: onboardingAgent

  datasource:
    url: jdbc:mysql://localhost:3306/onboardingdb
    username: root
    password: ANKUR5@.com
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect

  ai:
    google:
      genai:
        api-key: ${GEMINI_API_KEY}
        chat:
          model: gemini-2.5-flash-lite



logging:
  level:
    org.springframework.ai: TRACE
    org.springframework.ai.chat: TRACE
    org.springframework.ai.google.genai: TRACE

server:
  port: 8082
