spring:
  application:
    name: onboardingAgent

  datasource:
    url: jdbc:mysql://localhost:3306/onboardingdb
    username: root
    password: ANKUR5@.com
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect

  ai:
    google:
      genai:
        api-key: ${GEMINI_API_KEY}
        chat:
          model: gemini-2.5-flash-lite

  mail:
    host: smtp.gmail.com
    port: 587
    username: onboarding@company.com
    password: app-password
    properties:
      mail.smtp.auth: true
      mail.smtp.starttls.enable: true

logging:
  level:
    org.springframework.ai: TRACE
    org.springframework.ai.chat: TRACE
    org.springframework.ai.google.genai: TRACE

server:
  port: 8082
